name: PR Checks and Code Quality

on:
    pull_request:
        branches: ['main']

jobs:
    setup-and-install-dependencies:
        name: Setup and install dependencies
        runs-on: ubuntu-latest

        steps:
            - name: Checkout respository
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true

            - name: Install dependencies
              run: flutter pub get

    code-quality-check:
        name: Check code quality
        runs-on: ubuntu-latest
        needs: setup-and-install-dependencies

        steps:
            - name: Run flutter analyze
              run: flutter analyze

    run-tests:
        name: Run tests
        runs-on: ubuntu-latest
        needs: setup-and-install-dependencies

        steps:
            - name: Run flutter test
              run: flutter test
